# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statecoin50', '0003_coin_dateowned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='stURL',
        ),
        migrations.AddField(
            model_name='coin',
            name='stImg',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
